name: Migration notice.

on:
  pull_request:
#   paths:
#     - 'migrations/**'
#   types:
#     - closed

permissions:
  pull-requests: write

jobs:
  notice:
    runs-on: ubuntu-latest
#   if: github.event.pull_request.merged
    steps:
      - run: echo '${{ toJSON(github) }}'

      - run: |
          MESSAGE="$(mktemp)"
          cat << EOF > "$MESSAGE"
          マイグレーションの変更を含むPR \#${NUMBER} が ${BASE} へマージされました。
          \`git merge ${BASE}\` を実行の上、再度 push してください。
          EOF
          gh pr list --repo "$REPO" --base "$BASE" --label "$LABEL" --json number --jq '.[].number' --state open| xargs -n1 gh pr comment --body-file "$MESSAGE" --repo "$REPO"
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          BASE: ${{ github.base_ref }}
          URL: ${{ github.event.pull_request.html_url }}
          NUMBER: ${{ github.event.number }}
          TITLE: ${{ github.event.pull_request.title }}
          LABEL: migrate
